sudo: required
services:
    - docker

before_install:
    - docker build -t darren9352/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true darren9352/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-northeast-2-054704247757"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"